# Generated by Django 3.0.8 on 2020-09-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bathroom',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='bedroom',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exteriorfeatures',
            name='domestic_accomodation',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='exteriorfeatures',
            name='garage',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='exteriorfeatures',
            name='parking',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='interiorfeatures',
            name='bathroom',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='interiorfeatures',
            name='bedroom',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='interiorfeatures',
            name='kitchen',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='interiorfeatures',
            name='reception',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
