# Generated by Django 3.0.8 on 2020-10-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200930_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exteriorfeatures',
            name='domestic_accomodation',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exteriorfeatures',
            name='garage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exteriorfeatures',
            name='parking',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exteriorfeatures',
            name='pool',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3),
        ),
        migrations.AlterField(
            model_name='exteriorfeatures',
            name='security',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3),
        ),
        migrations.AlterField(
            model_name='interiorfeatures',
            name='bathroom',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='interiorfeatures',
            name='bedroom',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='interiorfeatures',
            name='kitchen',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='interiorfeatures',
            name='reception',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Rent', 'Rent'), ('Buy', 'Buy')], default='Sale', max_length=10),
        ),
    ]
