# Generated by Django 3.0.8 on 2020-10-02 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20201001_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShceduleTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('contact', models.CharField(max_length=20)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Property')),
            ],
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone1', models.CharField(max_length=20, verbose_name='Mobile Number 1')),
                ('phone2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile Number 2 (Optional)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
