# Generated by Django 3.0.8 on 2020-10-02 09:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_contactdetails_shceduletour'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactDetails',
            new_name='ContactDetail',
        ),
        migrations.RenameModel(
            old_name='ShceduleTour',
            new_name='ScheduleTour',
        ),
    ]
