# Generated by Django 3.0.8 on 2020-10-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201002_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletour',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='scheduletour',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
