# Generated by Django 3.0.8 on 2020-10-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201006_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='features',
        ),
        migrations.RemoveField(
            model_name='property',
            name='location',
        ),
        migrations.AddField(
            model_name='property',
            name='state_or_region',
            field=models.CharField(default='Greater Accra', max_length=100, verbose_name='State/Region'),
        ),
        migrations.AddField(
            model_name='property',
            name='town_or_city',
            field=models.CharField(default='Dansoman', max_length=100, verbose_name='Town/City'),
        ),
    ]
