# Generated by Django 3.0.8 on 2020-10-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201006_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletour',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
